# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.appointment_create import AppointmentCreate
from openapi_client.models.appointment_response import AppointmentResponse
from openapi_client.models.doctor_create import DoctorCreate
from openapi_client.models.doctor_response import DoctorResponse
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.slot_response import SlotResponse
from openapi_client.models.validation_error import ValidationError

