# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.doctors_api import DoctorsApi


class TestDoctorsApi(unittest.TestCase):
    """DoctorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DoctorsApi()

    def tearDown(self) -> None:
        pass

    def test_add_doctor_doctors_post(self) -> None:
        """Test case for add_doctor_doctors_post

        Add Doctor
        """
        pass

    def test_list_doctors_doctors_get(self) -> None:
        """Test case for list_doctors_doctors_get

        List Doctors
        """
        pass


if __name__ == '__main__':
    unittest.main()
