# coding: utf-8

# flake8: noqa

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AppointmentsApi",
    "DoctorsApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AppointmentCreate",
    "AppointmentResponse",
    "DoctorCreate",
    "DoctorResponse",
    "HTTPValidationError",
    "LocationInner",
    "SlotResponse",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.appointments_api import AppointmentsApi as AppointmentsApi
from openapi_client.api.doctors_api import DoctorsApi as DoctorsApi
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.appointment_create import AppointmentCreate as AppointmentCreate
from openapi_client.models.appointment_response import AppointmentResponse as AppointmentResponse
from openapi_client.models.doctor_create import DoctorCreate as DoctorCreate
from openapi_client.models.doctor_response import DoctorResponse as DoctorResponse
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.slot_response import SlotResponse as SlotResponse
from openapi_client.models.validation_error import ValidationError as ValidationError

